# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_conn import message_replicator_pb2 as message__replicator__pb2


class MessageReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Replicate = channel.unary_unary(
                '/message_replicator.MessageReplicator/Replicate',
                request_serializer=message__replicator__pb2.Message.SerializeToString,
                response_deserializer=message__replicator__pb2.Ack.FromString,
                )


class MessageReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=message__replicator__pb2.Message.FromString,
                    response_serializer=message__replicator__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message_replicator.MessageReplicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageReplicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message_replicator.MessageReplicator/Replicate',
            message__replicator__pb2.Message.SerializeToString,
            message__replicator__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
