# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_replicator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18message_replicator.proto\x12\x12message_replicator\"\"\n\x07Message\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x04\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x02(\x08\x32V\n\x11MessageReplicator\x12\x41\n\tReplicate\x12\x1b.message_replicator.Message\x1a\x17.message_replicator.Ack')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_replicator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=48
  _MESSAGE._serialized_end=82
  _ACK._serialized_start=84
  _ACK._serialized_end=106
  _MESSAGEREPLICATOR._serialized_start=108
  _MESSAGEREPLICATOR._serialized_end=194
# @@protoc_insertion_point(module_scope)
