# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_replicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_replicator.proto',
  package='message_replicator',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18message_replicator.proto\x12\x12message_replicator\"\"\n\x07Message\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x04\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x02(\x08\x32V\n\x11MessageReplicator\x12\x41\n\tReplicate\x12\x1b.message_replicator.Message\x1a\x17.message_replicator.Ack'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='message_replicator.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='message_replicator.Message.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='message_replicator.Message.id', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=82,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='message_replicator.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='message_replicator.Ack.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_replicator_pb2'
  # @@protoc_insertion_point(class_scope:message_replicator.Message)
  })
_sym_db.RegisterMessage(Message)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'message_replicator_pb2'
  # @@protoc_insertion_point(class_scope:message_replicator.Ack)
  })
_sym_db.RegisterMessage(Ack)



_MESSAGEREPLICATOR = _descriptor.ServiceDescriptor(
  name='MessageReplicator',
  full_name='message_replicator.MessageReplicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=108,
  serialized_end=194,
  methods=[
  _descriptor.MethodDescriptor(
    name='Replicate',
    full_name='message_replicator.MessageReplicator.Replicate',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEREPLICATOR)

DESCRIPTOR.services_by_name['MessageReplicator'] = _MESSAGEREPLICATOR

# @@protoc_insertion_point(module_scope)
